[package]
name = "ts"
version = "0.1.0"
authors = ["Anthony Leland <noreply@tonytins.xyz>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
isocal = "0.1"
directories = "3.0"
clap = { version = "3.0.0-beta.2", features = [ "wrap_help" ] }